POST https://localhost:5001/api/jogo/cadastrar
Content-Type: application/json
{
  "selecaoA": {
    "id": 1
  },
  "selecaoB": {
    "id": 2
  }
}
###
GET https://localhost:5001/api/jogo/listar

###
PATCH https://localhost:5001/api/jogo/alterar
Content-Type: application/json
{
  "id": 1,
  "placarA": 0,
  "placarB": 0
}